apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 647350340558.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 647350340558.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
