---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Demo-Cluster
  region: ap-northeast-1
fargateProfiles:
  - name: frontend-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: frontend-fargate
